Guess harder at where abf wants things

diff --git a/build b/build
--- a/build
+++ b/build
@@ -672,21 +672,26 @@ run generate-bootimg
 # Stuff in virtual filesystems should not make it to
 # root filesystems...
 for mp in /proc /sys /dev/pts /dev; do
-    [ -e "$OURDIR/$ROOTDIR$mp" ] && umount -Rq "$OURDIR/$ROOTDIR$mp" || :
+	[ -e "$OURDIR/$ROOTDIR$mp" ] && umount -Rq "$OURDIR/$ROOTDIR$mp" || :
 done
 run generate-rootfs
 
 if [ "$ABF" = "1" ]; then
-	# ABF will package anything left in $OURDIR -- so let's
-	# get rid of everything we don't want to ship and pull
-	# in the README file
-	[ -e device/${TARGET}/README.md ] && mv device/${TARGET}/README.md .
-	cd "$OURDIR"
-	rm -rf "$ROOTDIR" kernel device LICENSE PACKAGES *.rpm
-	rm -f build
-	# Apparently abf looks in results/ now...
-	mkdir results
-	mv * results/
+	# ABF packages everything in $HOME/output
+	# but it frequently forgets to remove what a previous
+	# run put there
+	mv "$HOME"/iso_build.log .
+	rm -rf "$HOME"/output
+	mkdir "$HOME"/output
+	mv iso_build.log "$HOME"/output
+	# Pull in the README file
+	[ -e device/${TARGET}/README.md ] && cp device/${TARGET}/README.md "$HOME"/output
+	# All of the following are allowed to fail because not
+	# every board needs/produces every one of them
+	mv *.img "$HOME"/output || :
+	mv *.tar* "$HOME"/output || :
+	# Clean up, we're no longer needed
+	rm -rf "$OURDIR"
 fi
 
 printf '%s\n' 'Building has finished.'
