make it compatible with RosaLinux

diff --git a/build b/build
--- a/build
+++ b/build
@@ -9,7 +9,7 @@ listTargets() {
 }
 usage() {
 	echo "Usage: $0 [ -v VERSION ] target"
-	echo "	-v: Use OpenMandriva VERSION (default: cooker)"
+	echo "	-v: Use ${BASE_DISTRO} VERSION (default: cooker)"
 	echo "	-K: Keep already existing build root (default: no)"
 	echo "Available targets:"
 	listTargets
@@ -82,7 +82,29 @@ WEAKDEPS=""
 ROOTFS_FS="f2fs"
 addpackageset core
 
-OMV_VERSION=cooker
+# for rosa it is http://abf-downloads.rosalinux.ru
+ABF_DOWNLOADS="${ABF_DOWNLOADS:-http://abf-downloads.openmandriva.org}"
+# for rosa it is rosa-linux-gnu
+BASE_TRIPLET="${BASE_TRIPLET:-openmandriva-linux-gnu}"
+# ver prefix needed only for rosalinux
+# should be just rosa
+VER_PREFIX=""
+# for rosa it is 2021.1
+OMV_VERSION="${OMV_VERSION:-cooker}"
+# for rosa it is RosaLinux
+BASE_DISTRO="${BASE_DISTRO:-OpenMandriva-Lx}"
+
+# install xldd only on OpenMandriva
+if [ $BASE_DISTRO == "OpenMandriva-Lx" ]; then
+	XLDD="xldd"
+	CROSS_ARM="cross-armv7hnl-openmandriva-linux-gnueabihf-gcc"
+else
+	XLDD=""
+	CROSS_ARM=""
+fi
+
+# for rosa it is rosa-repos-main
+PRE_PACKAGES="${PRE_PACKAGES:-distro-release-repos}"
 [ -z "$FINAL" ] && FINAL=false
 OS_VERSION=""
 IDENTIFIER=""
@@ -174,7 +196,7 @@ if ! [ -e device/$TARGET/config ]; then
 fi
 SHORTTARGET="$(basename $TARGET)"
 
-echo "Building OpenMandriva $OMV_VERSION image for $TARGET"
+echo "Building ${BASE_DISTRO} $OMV_VERSION image for $TARGET"
 run config
 
 # ===================================================================
@@ -196,7 +218,7 @@ if [ -z "$ARCH" ]; then
 	ARCH=aarch64
 fi
 
-TRIPLET=$ARCH-openmandriva-linux-gnu
+TRIPLET=$ARCH-${BASE_TRIPLET}
 case $ARCH in
 aarch64)
 	KERNELARCH=arm64
@@ -266,7 +288,7 @@ if [ -n "$KERNEL" ]; then
 	if [ "$ARCH" = "aarch64" ]; then
 		# Many aarch64 kernels (e.g. rk3399) need a 32-bit ARM compiler
 		# to target a helper Cortex-M0 etc.
-		HOSTDEPS="$HOSTDEPS cross-armv7hnl-openmandriva-linux-gnueabihf-gcc"
+		HOSTDEPS="$HOSTDEPS ${CROSS_ARMHF}"
 	fi
 fi
 $NATIVEBUILD || HOSTDEPS="$HOSTDEPS qemu-static-$QEMUARCH"
@@ -281,7 +303,7 @@ if [ -n "$HOSTDEPS" ] && [ -z "$KEEP_OLD_ROOT" ]; then
 	if ! dnf -y --refresh --nogpgcheck install $HOSTDEPS; then
 		for i in $HOSTDEPS; do
 			if ! rpm -q $i &>/dev/null; then
-				echo "Couldn't install needed HOST tools. Make sure you're running current OpenMandriva"
+				echo "Couldn't install needed HOST tools. Make sure you're running current ${BASE_DISTRO}"
 				echo "or install $i manually"
 				exit 1
 			fi
@@ -289,7 +311,10 @@ if [ -n "$HOSTDEPS" ] && [ -z "$KEEP_OLD_ROOT" ]; then
 	fi
 
 	# Make sure the binfmt handler knows about any qemu-static bits we may have installed...
-	echo ':aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-aarch64-static:' >/proc/sys/fs/binfmt_misc/register || :
+	if [ !"$ARCH" = "aarch64" ]; then
+		HOSTDEPS="$HOSTDEPS"
+		echo ':aarch64:M::\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xb7:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff:/usr/bin/qemu-aarch64-static:' >/proc/sys/fs/binfmt_misc/register || :
+	fi
 fi
 
 # ===================================================================
@@ -434,7 +459,7 @@ fi
 
 # First of all let's find the right repo list...
 
-ROOTDIR="OpenMandriva-$OMV_VERSION-$ARCH-root"
+ROOTDIR="${BASE_DISTRO}-$OMV_VERSION-$ARCH-root"
 
 # Make sure we don't have any dangerous bind mounts left...
 cleanup() {
@@ -461,10 +486,9 @@ if [ ! -d "$ROOTDIR" ]; then
 	# Poor man's version of "dnf install --installroot=" --
 	# need to get the repository configs from rpm packages
 	# without having the repositories configured...
-	PKGS=http://abf-downloads.openmandriva.org/$OMV_VERSION/repository/$ARCH/main/release/
+	PKGS=${ABF_DOWNLOADS}/${VER_PREFIX}${OMV_VERSION}/repository/$ARCH/main/release/
 	echo $PKGS
 	curl -s -L $PKGS |grep '^<a' |cut -d'"' -f2 >PACKAGES
-	PRE_PACKAGES="distro-release-repos"
 	for i in $PRE_PACKAGES; do
 		P=$(grep "^$i-[0-9].*" PACKAGES |tail -n1)
 		if [ "$?" != "0" ]; then
@@ -493,7 +517,7 @@ if [ ! -d "$ROOTDIR" ]; then
 	# FIXME workaround for ldd being broken on aarch64 (at least in qemu)
 	# (causes dracut to miss bash's dependencies)
 	if [ "$ARCH" = "aarch64" ]; then
-		PACKAGES="$PACKAGES xldd"
+		PACKAGES="$PACKAGES ${XLDD}"
 	fi
 	if [ "$NEED_INITRD" != "no" ]; then
 		PACKAGES="$PACKAGES dracut"
@@ -750,9 +774,9 @@ fi
 
 # Reinstall distro-release-repos to get mirrors back
 
-[ -z $KEEP_OLD_ROOT ] && dnf -y reinstall --installroot="$OURDIR/$ROOTDIR" --releasever=$OMV_VERSION --forcearch=$ARCH distro-release-repos
+[ -z $KEEP_OLD_ROOT ] && dnf -y reinstall --installroot="$OURDIR/$ROOTDIR" --releasever=$OMV_VERSION --forcearch=$ARCH ${PRE_PACKAGES}
 [ -d "$OURDIR/$ROOTDIR/var/cache/dnf" ] && rm -rf "$OURDIR/$ROOTDIR/var/cache/dnf/*"
-BASENAME="OpenMandriva-Lx-${SHORTTARGET}-${OS_VERSION}"
+BASENAME="${BASE_DISTRO}-${SHORTTARGET}-${OS_VERSION}"
 
 # generate-bootimg and generate-rootfs can write to results.
 # Wipe it clean and make sure it exists
