Various Rock Pi fixes, compress images

diff --git a/build b/build
--- a/build
+++ b/build
@@ -292,10 +292,12 @@ if [ -n "$KERNEL" ]; then
 	[ -e scripts/lld-version.sh ] && sed -i -e "s,' ' -f 2,' ' -f 4," scripts/lld-version.sh
 	PN=1
 	for i in ${OURDIR}/device/${TARGET}/kernel-patches/*.patch ${OURDIR}/device/${TARGET}/kernel-patches/*.diff; do
+		echo "Applying $(basename $i)" >&2
 		[ -e "$i" ] && patch -p1 -b -z .b${PN}~ <$i
 		PN=$((PN+1))
 	done
 	for i in ${OURDIR}/device/${TARGET}/kernel-patches/*.gitpatch; do
+		echo "Applying $(basename $i)" >&2
 		[ -e "$i" ] && git apply $i
 	done
 	run download_kernel_extras
@@ -685,6 +687,8 @@ for mp in /proc /sys /dev/pts /dev; do
 done
 run generate-rootfs
 
+xz -9ef *.img || :
+
 if [ "$ABF" = "1" ]; then
 	# ABF looks in /home/omv, but sets HOME to /root
 	export HOME="/home/omv"
@@ -697,12 +701,13 @@ if [ "$ABF" = "1" ]; then
 	mv iso_build.log "$HOME"/output || :
 	# Pull in the README file
 	[ -e device/${TARGET}/README.md ] && cp device/${TARGET}/README.md "$HOME"/output
+	[ -e device/${TARGET}/write2sd ] && cp device/${TARGET}/README.md "$HOME"/output
 	# All of the following are allowed to fail because not
 	# every board needs/produces every one of them
-	mv *.img "$HOME"/output || :
+	mv *.img* "$HOME"/output || :
 	mv *.tar* "$HOME"/output || :
-	# Clean up, we're no longer needed
-	rm -rf "$OURDIR"
+	# Clean up, we're no longer needed [looks like abf takes care of this]
+	# rm -rf "$OURDIR"
 fi
 
 printf '%s\n' 'Building has finished.'
